// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.b2.ankiety.model;

import com.b2.ankiety.model.Choice;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Choice_Roo_Configurable {
    
    declare @type: Choice: @Configurable;
    
}
